package Mapeamentos;
// Generated Jun 5, 2019 11:54:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,schema="public"
)
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String nomeCategoria;
     private Set<Produto> produtos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(int idCategoria, String nomeCategoria, Set<Produto> produtos) {
       this.idCategoria = idCategoria;
       this.nomeCategoria = nomeCategoria;
       this.produtos = produtos;
    }
   
     @Id 

    
    @Column(name="id_categoria", unique=true, nullable=false)
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="nome_categoria", length=20)
    public String getNomeCategoria() {
        return this.nomeCategoria;
    }
    
    public void setNomeCategoria(String nomeCategoria) {
        this.nomeCategoria = nomeCategoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


