package Mapeamentos;
// Generated Jun 5, 2019 11:54:32 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.math.BigDecimal;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,schema="public"
)
public class Compra  implements java.io.Serializable {


     private int idCompra;
     private Produto produto;
     private Usuario usuario;
     private Integer quantidadeCompra;
     private BigDecimal valor;
     private Date dataCompra;

    public Compra() {
    }

	
    public Compra(int idCompra) {
        this.idCompra = idCompra;
    }
    public Compra(int idCompra, Produto produto, Usuario usuario, Integer quantidadeCompra, BigDecimal valor,Date dataCompra) {
       this.idCompra = idCompra;
       this.produto = produto;
       this.usuario = usuario;
       this.quantidadeCompra = quantidadeCompra;
       this.valor = valor;
       this.dataCompra = dataCompra;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_compra", unique=true, nullable=false)
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="codigo")
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cpf")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="quantidade_compra")
    public Integer getQuantidadeCompra() {
        return this.quantidadeCompra;
    }
    
    public void setQuantidadeCompra(Integer quantidadeCompra) {
        this.quantidadeCompra = quantidadeCompra;
    }

    
    @Column(name="valor", precision=12, scale=2)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    
    @Column(name = "data_compra")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDataCompra() {
        return dataCompra;
    }

    public void setDataCompra(Date dataCompra) {
        this.dataCompra = dataCompra;
    }




}


